AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: ChefConnect API
Resources:
  ApiTarget:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "dev"
      Domain:
        - DomainName: example.com # Required
          Route53:
            EvaluateTargetHealth: true # Default to false
          EndpointConfiguration: REGIONAL
          BasePath: "/"

  LambdaTarget:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: bin/main
      VpcConfig:
        SubnetIds:
          - "subnet-3fc89a17"
          - "subnet-6a3db166"
        SecurityGroupIds:
          - "sg-0a8152dc68b10c5e4"
          - "sg-0a8152dc68b10c5e4"
      Environment:
        Variables:
          IS_LAMBDA: true
          DB_HOST: "ip-172-31-12-209.ec2.internal"
          DB_PORT: 9080
      Events:
        RootHandler:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiTarget
            Path: "/{proxy+}"
            Method: any

  Route53Entry:
    Type: AWS::Route53::RecordSet
    Condition: CreateRoute53
    Properties:
      AliasTarget:
        DNSName: !GetAtt FrontendCloudfrontDistribution.DomainName
        HostedZoneId: Z04564473TXYVWUJFRVM3
      HostedZoneId: Z04564473TXYVWUJFRVM3
      Name: "api.recipe.veraciousdata.io"
      Type: A

Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
