name: Build and Deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Source checkout
        uses: actions/checkout@master

      - name: Setup Golang env
        uses: actions/setup-go@v1
        with:
          go-version: "1.14.4" # The Go version to download (if necessary) and use.

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install aws-sam-cli && sudo apt update && sudo apt install build-essential

      - name: Configure AWS credentials [LAB]
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Build & Deploy to AWS
        run: |
          make buildLambda
          sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket sam-chefconnect-dev
          sam deploy --template-file packaged.yaml --stack-name sam-chefconnect-dev --capabilities CAPABILITY_NAMED_IAM --region us-east-1
