name: Build and Deploy
on:
  push:
    branches:
      - dev
      - prod
jobs:
  dev-deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Source checkout
        uses: actions/checkout@master

      - name: Setup Golang env
        uses: actions/setup-go@v1
        with:
          go-version: "1.14.4"

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install aws-sam-cli==1.19.1 && sudo apt update && sudo apt install build-essential

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Configure private MDBPro SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.MDBPRO_SSH_KEY }}

      - name: Build infra/code then deploy
        run: |
          make buildLambda
          sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket chefconnect-cfn-dev
          sam deploy --template-file packaged.yaml --stack-name chefconnect-dev --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM --region us-east-1 --parameter-overrides Environment=${GITHUB_REF##*/} DgraphAuthToken=${{ secrets.DGRAPH_TOKEN_DEV }} JwtSecretKey=${{ secrets.JWT_SECRET_DEV }}
          cd frontend/
          ssh-keyscan -t rsa -H git.mdbootstrap.com >> ~/.ssh/known_hosts
          npm install
          npm run build
          aws s3 sync dist/* s3://$(aws cloudformation describe-stacks --stack-name chefconnect-dev | jq '.Stacks[0].Outputs[] | select(.OutputKey == "StaticBucket") | .OutputValue')

  prod-deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Source checkout
        uses: actions/checkout@master

      - name: Setup Golang env
        uses: actions/setup-go@v1
        with:
          go-version: "1.14.4"

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Build to Dev
        run: |
          make buildLambda
          sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket sam-chefconnect-dev
          sam deploy --template-file packaged.yaml --stack-name sam-chefconnect-dev --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM --region us-east-1 --parameter-overrides Environment=${GITHUB_REF##*/} DgraphAuthToken=${{ secrets.DGRAPH_TOKEN_DEV }} JwtSecretKey=${{ secrets.JWT_SECRET_PROD }}